# Generated by Django 2.2 on 2020-04-04 10:33

import details.models
from django.db import migrations, models
import djongo.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=7, null=True)),
                ('faculty_name', models.CharField(max_length=30, null=True)),
                ('designation', models.CharField(max_length=30, null=True)),
                ('department', models.CharField(max_length=30, null=True)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('qualifications', djongo.models.fields.ArrayField(model_container=details.models.Qualification, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(null=True)),
                ('office', models.CharField(max_length=30, null=True)),
                ('biography', models.TextField(null=True)),
                ('specializations', djongo.models.fields.ArrayField(model_container=details.models.Topic, null=True)),
                ('teaching_interests', djongo.models.fields.ArrayField(model_container=details.models.Topic, null=True)),
                ('accomplishments', djongo.models.fields.ArrayField(model_container=details.models.Topic, null=True)),
                ('publications', djongo.models.fields.ArrayField(model_container=details.models.Publication, null=True)),
                ('awards', djongo.models.fields.ArrayField(model_container=details.models.Award, null=True)),
                ('organizations', djongo.models.fields.ArrayField(model_container=details.models.Organization, null=True)),
                ('faculty_type', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
