# Generated by Django 2.2.11 on 2020-04-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='FacultyInfo',
        ),
    ]
