# Generated by Django 2.2.11 on 2020-04-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20200403_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyInfo',
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'faculties'},
        ),
    ]
