# Generated by Django 2.1.11 on 2020-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20200406_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
