# Generated by Django 2.2.11 on 2020-04-04 14:57

import details.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20200404_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_title', models.CharField(max_length=30)),
                ('credential_id', models.CharField(max_length=100)),
                ('credential_url', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('issuing_organization', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=djongo.models.fields.ArrayField(model_container=details.models.Topic, null=True),
        ),
    ]
