# Generated by Django 2.1.11 on 2020-04-09 16:34

import details.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20200409_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='specializations',
            field=djongo.models.fields.ArrayField(model_container=details.models.Topic, model_form_class=details.models.TopicForm, null=True),
        ),
    ]
