# Generated by Django 2.2.11 on 2020-04-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_remove_faculty_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CE', 'CE'), ('IT', 'IT'), ('IC', 'IC'), ('CL', 'CL'), ('EC', 'EC'), ('CH', 'CH'), ('MH', 'MH')], default='CE', max_length=2),
        ),
    ]
