# Generated by Django 2.2.11 on 2020-04-04 17:06

import details.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20200404_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=djongo.models.fields.ArrayField(model_container=details.models.Topic, null=True),
        ),
    ]
